# Generated by Django 6.0.6 on 2026-07-22 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0002_alter_pessoa_setores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
