# Generated by Django 6.0.6 on 2026-07-23 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0003_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='text_alter',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='setores',
            field=models.ManyToManyField(related_name='pessoas', to='ramais.setor'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='setor',
            name='ramal',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='O ramal deve conter exatamente 4 números.', regex='^\\d{4}$')]),
        ),
    ]
